import { User, CarServiceOrder, ServiceItem, calculateMechanicEarning } from '../types';
import { hashPassword } from './crypto';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-owner-1',
    firstName: 'ზვიადი',
    lastName: '',
    username: 'zviadi',
    passwordHash: hashPassword('zviadi123'),
    role: 'super_admin',
    enabledModules: ['shop', 'day_closing', 'reports'],
    createdAt: '2026-01-01T10:00:00Z',
  },
  {
    id: 'usr-admin-1',
    firstName: 'გიორგი',
    lastName: 'იმედაშვილი',
    username: 'admin',
    passwordHash: hashPassword('admin'),
    role: 'admin',
    enabledModules: ['shop', 'day_closing', 'reports'],
    createdAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'usr-dev-1',
    firstName: 'გიორგი',
    lastName: 'იმედაშვილი',
    username: 'imedo',
    passwordHash: hashPassword('imed458'),
    role: 'developer',
    enabledModules: ['shop', 'day_closing', 'reports'],
    createdAt: '2026-01-01T09:00:00Z',
  },
  {
    id: 'usr-mech-1',
    firstName: 'გიორგი',
    lastName: 'ბერიძე',
    username: 'giorgi',
    passwordHash: hashPassword('pass123'),
    role: 'mechanic',
    enabledModules: [],
    createdAt: '2026-05-02T12:00:00Z',
  },
  {
    id: 'usr-mech-2',
    firstName: 'თემო',
    lastName: 'შონია',
    username: 'temo',
    passwordHash: hashPassword('pass123'),
    role: 'mechanic',
    enabledModules: [],
    createdAt: '2026-05-02T12:30:00Z',
  },
];

export const INITIAL_ORDERS: CarServiceOrder[] = [
  {
    id: 'ord-101',
    date: '2026-05-26',
    carBrand: 'MERCEDES-BENZ ACTROS',
    carNumber: 'GE-777-ZZ',
    clientFullName: 'ირაკლი გელაშვილი',
    clientPhone: '599123456',
    problemDescription: 'სავალი ნაწილის შემოწმება და დიაგნოსტიკა, ჩეკის წაკითხვა',
    status: 'completed',
    paymentStatus: 'paid',
    createdBy: 'usr-admin-1',
    createdAt: '2026-05-26T09:15:00Z',
    updatedAt: '2026-05-26T14:30:00Z',
  },
  {
    id: 'ord-102',
    date: '2026-05-26',
    carBrand: 'SCANIA R500',
    carNumber: 'XX-888-BB',
    clientFullName: 'ნიკოლოზ მჭედლიშვილი',
    clientPhone: '595987654',
    problemDescription: 'ძრავზე ზეთის გაჟონვა, ელექტროობის შემოწმება',
    status: 'pending',
    paymentStatus: 'unpaid',
    createdBy: 'usr-admin-1',
    createdAt: '2026-05-26T10:45:00Z',
    updatedAt: '2026-05-26T11:00:00Z',
  },
  {
    id: 'ord-103',
    date: '2026-05-25',
    carBrand: 'MAN TGX',
    carNumber: 'AQ-010-QA',
    clientFullName: 'ნინო დევდარიანი',
    clientPhone: '555332211',
    problemDescription: 'კონდიციონერი არ უბერავს ცივ ჰაერს',
    status: 'completed',
    paymentStatus: 'paid',
    createdBy: 'usr-admin-1',
    createdAt: '2026-05-25T11:00:00Z',
    updatedAt: '2026-05-25T16:20:00Z',
  },
  {
    id: 'ord-104',
    date: '2026-05-24',
    carBrand: 'VOLVO FH',
    carNumber: 'MB-400-EE',
    clientFullName: 'ლევან კაპანაძე',
    clientPhone: '591554433',
    problemDescription: 'წინა ფარები არ ინთება, ელექტროობის პრობლემაა',
    status: 'completed',
    paymentStatus: 'paid',
    createdBy: 'usr-admin-1',
    createdAt: '2026-05-24T08:30:00Z',
    updatedAt: '2026-05-24T12:00:00Z',
  },
  {
    id: 'ord-105',
    date: '2026-05-23',
    carBrand: 'DAF XF',
    carNumber: 'HF-987-AA',
    clientFullName: 'დავით კობახიძე',
    clientPhone: '577443322',
    problemDescription: 'ზეთის შეცვლა ძრავში, ფილტრების განახლება',
    status: 'completed',
    paymentStatus: 'unpaid',
    createdBy: 'usr-admin-1',
    createdAt: '2026-05-23T14:20:00Z',
    updatedAt: '2026-05-23T15:30:00Z',
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    orderId: 'ord-101',
    serviceType: 'diagnostic',
    description: 'კომპიუტერული სრული დიაგნოსტიკა',
    price: 50,
    mechanicId: 'usr-mech-1',
    mechanicEarning: calculateMechanicEarning('diagnostic', 50),
    createdAt: '2026-05-26T10:00:00Z',
  },
  {
    id: 'srv-2',
    orderId: 'ord-101',
    serviceType: 'electromechanics',
    description: 'ABS სისტემის შემოწმება',
    price: 120,
    mechanicId: 'usr-mech-1',
    mechanicEarning: calculateMechanicEarning('electromechanics', 120),
    createdAt: '2026-05-26T12:00:00Z',
  },
  {
    id: 'srv-3',
    orderId: 'ord-102',
    serviceType: 'diagnostic',
    description: 'ძრავის კოდების წაკითხვა',
    price: 60,
    mechanicId: 'usr-mech-2',
    mechanicEarning: calculateMechanicEarning('diagnostic', 60),
    createdAt: '2026-05-26T11:15:00Z',
  },
  {
    id: 'srv-4',
    orderId: 'ord-103',
    serviceType: 'other',
    description: 'ფრეონის დამატება',
    price: 90,
    mechanicId: 'usr-mech-1',
    mechanicEarning: calculateMechanicEarning('other', 90),
    createdAt: '2026-05-25T13:00:00Z',
  },
  {
    id: 'srv-5',
    orderId: 'ord-104',
    serviceType: 'electromechanics',
    description: 'ფარების ბლოკების რემონტი',
    price: 260,
    mechanicId: 'usr-mech-2',
    mechanicEarning: calculateMechanicEarning('electromechanics', 260),
    createdAt: '2026-05-24T10:00:00Z',
  },
  {
    id: 'srv-6',
    orderId: 'ord-105',
    serviceType: 'other',
    description: 'ძრავში ზეთისა და ფილტრების შეცვლა',
    price: 80,
    mechanicId: 'usr-mech-1',
    mechanicEarning: calculateMechanicEarning('other', 80),
    createdAt: '2026-05-23T14:40:00Z',
  },
];
